### ISSUE TITLE
Keep shooter spinning in Auto

### ISSUE THREAD

**Issue by mark-has-it** [panthertech292/2022_r#10]
AutoMain.java should keep the shooter running at all times until we are out of balls. It currently waits till after the drive to spin up and allows the shooter to spin down between shots. 

Maybe run run shooter in parallel with the back up and pick up ball commands?

    addCommands(
    new parallel(drive back and spin shooter), //Drive to shooting position
    new RunShooterBelt(s_ShooterSubsystem, s_BeltSubsystem, 0.26, 0.26, 1420, BeltConstants.kFrontBeltSpeed, BeltConstants.kBackBeltSpeed).withTimeout(3), //Run the shooter
    new parallel (put arm down and spin shooter).withTimeout(0.5), //Put the arm down
    new parallel(drive back, run pickup and belts and spin shooter), //Drive with pickup down to get ball
    new RunShooterBelt(s_ShooterSubsystem, s_BeltSubsystem, 0.28, 0.28, 1550, BeltConstants.kFrontBeltSpeed, BeltConstants.kBackBeltSpeed).withTimeout(3), //Run the shooter
    new PickupArmUp(s_PickupSubsystem, PickupConstants.kPickupArmSpeedUp).withTimeout(2), //Raise arm
    new AutoEncoderDriveForBack(s_DriveSubsystem, 25, .4) //Drive back to get off line
    );

Or something like that...

**Comment by DBNines** [comment]
Added code for REVing shooter during auto.
